Export DICOM images from AltaDB
redbrick-ai/altadb-sdk pull request #6
Opened 2024-11-12 11:40 UTC by AvanishCodes

Command
---------
`altadb export <datasetname> <path>`

Validations
---------
- [X] Tested with DICOM image of multiple `SeriesInstanceUID`.
- [X] Tested with dataset of images more than number of images received in Single page response.
- [ ] Tested with RGB DICOM Image.
- [ ] Tested for Diff modality images.
- - [ ] CT
- - [ ] MR

2024-11-13 11:24 UTC, pritamrungta requested changes

2024-11-14 06:15 UTC, AvanishCodes commented on altadb/utils/files.py
> +def create_dicom_dataset(
Is it fine to take the `aiohttp.ClientSession` object as the input too?

2024-11-14 07:26 UTC, AvanishCodes commented on altadb/export/public.py
> +        if not ignore_existing:
To not download a series if it exists.

2024-11-15 05:43 UTC, AvanishCodes commented on altadb/cli/command/query.py
> +                    first=number,
Use `PaginatedResponse`.

2024-11-16 03:45 UTC, AvanishCodes commented on altadb/export/public.py
> +        if not ignore_existing:
Removing this feat.

2024-11-16 03:46 UTC, AvanishCodes commented on altadb/utils/files.py
> +def create_dicom_dataset(
Not taking `aiohttp.ClientSession` as in input parameter.

2024-11-21 11:35 UTC, pritamrungta commented
merging without approval

2024-11-21 11:35 UTC, merged